var searchData=
[
  ['f4vi1',['F4VI1',['../group__boards__f4vi1.html',1,'']]],
  ['firefly_20board',['Firefly Board',['../group__boards__firefly.html',1,'']]],
  ['fox',['fox',['../group__boards__fox.html',1,'']]],
  ['freescale_20frdm_2dkw41z_20board',['Freescale FRDM-KW41Z Board',['../group__boards__frdm-kw41z.html',1,'']]],
  ['feetech_20driver',['Feetech driver',['../group__drivers__feetech.html',1,'']]],
  ['flash_20memory_20driver',['Flash memory driver',['../group__drivers__flashrom.html',1,'']]],
  ['fxos8700_203_2daxis_20accelerometer_2fmagnetometer',['FXOS8700 3-axis accelerometer/magnetometer',['../group__drivers__fxos8700.html',1,'']]],
  ['fxos8700_20accelerometer_2fmagnetometer_20driver_20compile_20configuration',['FXOS8700 accelerometer/magnetometer driver compile configuration',['../group__drivers__fxos8700__config.html',1,'']]],
  ['flashpage_20mtd',['Flashpage MTD',['../group__drivers__mtd__flashpage.html',1,'']]],
  ['flash_20page_20driver',['Flash page driver',['../group__drivers__periph__flashpage.html',1,'']]],
  ['forwarding_20information_20base_20_28fib_29',['Forwarding Information Base (FIB)',['../group__net__fib.html',1,'']]],
  ['forwarding_20table',['Forwarding table',['../group__net__gnrc__ipv6__nib__ft.html',1,'']]],
  ['fragment_20size_20hint',['Fragment size hint',['../group__net__gnrc__sixlowpan__frag__hint.html',1,'']]],
  ['fragmentation_20and_20reassembly_20statistics',['Fragmentation and reassembly statistics',['../group__net__gnrc__sixlowpan__frag__stats.html',1,'']]],
  ['fat_20file_20system',['FAT file system',['../group__pkg__fatfs.html',1,'']]],
  ['flatbuffers',['FlatBuffers',['../group__pkg__flatbuffers.html',1,'']]],
  ['fletcher16',['Fletcher16',['../group__sys__checksum__fletcher16.html',1,'']]],
  ['fletcher32',['Fletcher32',['../group__sys__checksum__fletcher32.html',1,'']]],
  ['fatfs_20integration',['FatFs integration',['../group__sys__fatfs.html',1,'']]],
  ['fractional_20integer_20operations',['Fractional integer operations',['../group__sys__frac.html',1,'']]],
  ['file_20systems',['File systems',['../group__sys__fs.html',1,'']]],
  ['fuzzing_20utilities',['FUZZING utilities',['../group__sys__fuzzing.html',1,'']]],
  ['fowler–noll–vo',['Fowler–Noll–Vo',['../group__sys__hashes__fnv.html',1,'']]]
];
