var searchData=
[
  ['mikroe_206lowpan_20clicker',['MikroE 6LoWPAN Clicker',['../group__boards__6lowpan-clicker.html',1,'']]],
  ['msb_2d430_20common',['MSB-430 common',['../group__boards__common__msb-430.html',1,'']]],
  ['microchip_20saml1x',['Microchip SAML1X',['../group__boards__common__saml1x.html',1,'']]],
  ['mh_2det_20live_20minikit',['MH-ET LIVE MiniKit',['../group__boards__esp32__mh-et-live-minikit.html',1,'']]],
  ['maple_2dmini',['maple-mini',['../group__boards__maple-mini.html',1,'']]],
  ['mbed_20lpc1768_20development_20kit',['mbed LPC1768 development kit',['../group__boards__mbed__lpc1768.html',1,'']]],
  ['mcb2388_20evaluation_20board',['MCB2388 Evaluation Board',['../group__boards__mcb2388.html',1,'']]],
  ['mega1284p_2dxplained',['Mega1284P-Xplained',['../group__boards__mega-xplained.html',1,'']]],
  ['microduino_20corerf',['Microduino CoreRF',['../group__boards__microduino-corerf.html',1,'']]],
  ['msb_2d430',['MSB-430',['../group__boards__msb430.html',1,'']]],
  ['msb_2d430h',['MSB-430H',['../group__boards__msb430h.html',1,'']]],
  ['msb_2da2',['MSB-A2',['../group__boards__msba2.html',1,'']]],
  ['msb_2diot',['MSB-IoT',['../group__boards__msbiot.html',1,'']]],
  ['microchip_20sam_20e54_20xplained_20pro',['Microchip SAM E54 Xplained Pro',['../group__boards__same54-xpro.html',1,'']]],
  ['microchip_20saml10_20xplained_20pro',['Microchip SAML10 Xplained Pro',['../group__boards__saml10-xpro.html',1,'']]],
  ['microchip_20saml11_20xplained_20pro',['Microchip SAML11 Xplained Pro',['../group__boards__saml11-xpro.html',1,'']]],
  ['microchip_20sam_20r34_20xplained_20pro',['Microchip SAM R34 Xplained Pro',['../group__boards__samr34-xpro.html',1,'']]],
  ['miscellaneous_20device_20configurations',['Miscellaneous Device Configurations',['../group__config__drivers__misc.html',1,'']]],
  ['mailboxes',['Mailboxes',['../group__core__mbox.html',1,'']]],
  ['messaging_20_2f_20ipc',['Messaging / IPC',['../group__core__msg.html',1,'']]],
  ['mutex',['Mutex',['../group__core__sync__mutex.html',1,'']]],
  ['microchip_20mips_20common',['Microchip MIPS common',['../group__cpu__mips__pic32__common.html',1,'']]],
  ['microchip_20samd5x_2fsame5x',['Microchip SAMD5x/SAME5x',['../group__cpu__samd5x.html',1,'']]],
  ['microchip_20saml10_2fsaml11',['Microchip SAML10/SAML11',['../group__cpu__saml1x.html',1,'']]],
  ['microchip_20ata8520e_20transceiver',['Microchip ATA8520E transceiver',['../group__drivers__ata8520e.html',1,'']]],
  ['maxim_20ds75lx_20temperature_20sensor',['Maxim DS75LX temperature sensor',['../group__drivers__ds75lx.html',1,'']]],
  ['mag3110_203_2daxis_20digital_20magnetometer',['MAG3110 3-Axis Digital Magnetometer',['../group__drivers__mag3110.html',1,'']]],
  ['mag3110_20magnetometer_20driver_20compile_20configuration',['MAG3110 Magnetometer driver compile configuration',['../group__drivers__mag3110__config.html',1,'']]],
  ['mh_2dz19_20co2_20sensor',['MH-Z19 CO2 sensor',['../group__drivers__mhz19.html',1,'']]],
  ['miscellaneous_20drivers',['Miscellaneous Drivers',['../group__drivers__misc.html',1,'']]],
  ['mma7660_20accelerometer',['MMA7660 Accelerometer',['../group__drivers__mma7660.html',1,'']]],
  ['mma8x5x_20accelerometer',['MMA8x5x Accelerometer',['../group__drivers__mma8x5x.html',1,'']]],
  ['mma8x5x_20accelerometer_20driver_20compile_20configuration',['MMA8x5x Accelerometer driver compile configuration',['../group__drivers__mma8x5x__config.html',1,'']]],
  ['motor_5fdriver_20driver_20compile_20configuration',['Motor_Driver driver compile configuration',['../group__drivers__motor__driver__config.html',1,'']]],
  ['mpl3115a2_20pressure_20sensor',['MPL3115A2 Pressure Sensor',['../group__drivers__mpl3115a2.html',1,'']]],
  ['mpl3115a2_20pressure_20sensor_20driver_20compile_20configuration',['MPL3115A2 Pressure Sensor driver compile configuration',['../group__drivers__mpl3115a2__config.html',1,'']]],
  ['mpu_2d9x50_20_28mpu9150_20and_20mpu9250_29_20accelerometer_2fmagnetometer_2fgyroscope',['MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope',['../group__drivers__mpu9x50.html',1,'']]],
  ['mq_2d3_20alcohol_20tester',['MQ-3 Alcohol Tester',['../group__drivers__mq3.html',1,'']]],
  ['mrf24j40_20based_20drivers',['MRF24J40 based drivers',['../group__drivers__mrf24j40.html',1,'']]],
  ['mrf24j40_20driver_20compile_20configuration',['mrf24j40 driver compile configuration',['../group__drivers__mrf24j40__config.html',1,'']]],
  ['memory_20technology_20device',['Memory Technology Device',['../group__drivers__mtd.html',1,'']]],
  ['mtd_20wrapper_20for_20at24cxxx_20family_20of_20i2c_2deeproms',['MTD wrapper for AT24cxxx family of I2C-EEPROMs',['../group__drivers__mtd__at24cxxx.html',1,'']]],
  ['mtd_20wrapper_20for_20at25xxx_20family_20of_20spi_2deeproms',['MTD wrapper for AT25xxx family of SPI-EEPROMs',['../group__drivers__mtd__at25xxx.html',1,'']]],
  ['mtd_20address_20mapper',['MTD address mapper',['../group__drivers__mtd__mapper.html',1,'']]],
  ['mtd_20wrapper_20for_20sdcard_5fspi',['mtd wrapper for sdcard_spi',['../group__drivers__mtd__sdcard.html',1,'']]],
  ['multimedia_20device_20drivers',['Multimedia Device Drivers',['../group__drivers__multimedia.html',1,'']]],
  ['my9221_20led_20controller',['MY9221 LED controller',['../group__drivers__my9221.html',1,'']]],
  ['mqtt_2dsn_20client_20_28asymcute_29',['MQTT-SN Client (Asymcute)',['../group__net__asymcute.html',1,'']]],
  ['mqtt_2dsn_20client_20_28emcute_29',['MQTT-SN Client (emCute)',['../group__net__emcute.html',1,'']]],
  ['mailbox_20ipc_20extension',['Mailbox IPC extension',['../group__net__gnrc__netapi__mbox.html',1,'']]],
  ['mqtt_2dsn_20defines',['MQTT-SN Defines',['../group__net__mqttsn.html',1,'']]],
  ['microchip_20cryptoauthentication_20library',['Microchip CryptoAuthentication Library',['../group__pkg__cryptoauthlib.html',1,'']]],
  ['micro_2decc_20for_20riot',['Micro-ECC for RIOT',['../group__pkg__micro__ecc.html',1,'']]],
  ['micropython_20riot_20port',['MicroPython RIOT port',['../group__pkg__micropython.html',1,'']]],
  ['monocypher_20cryptographic_20library',['Monocypher cryptographic library',['../group__pkg__monocypher.html',1,'']]],
  ['multimedia_20driver_20auto_2dinitialization',['Multimedia driver auto-initialization',['../group__sys__auto__init__multimedia.html',1,'']]],
  ['millisecond_20interval_20event_20timers',['Millisecond interval event timers',['../group__sys__evtimer.html',1,'']]],
  ['md5',['MD5',['../group__sys__hashes__md5.html',1,'']]],
  ['math_20libraries_20and_20utilities',['Math libraries and utilities',['../group__sys__math.html',1,'']]],
  ['matstat_20_2d_20integer_20mathematical_20statistics_20library',['Matstat - Integer mathematical statistics library',['../group__sys__matstat.html',1,'']]],
  ['memory_20array_20allocator',['memory array allocator',['../group__sys__memarray.html',1,'']]],
  ['memory_20management',['Memory management',['../group__sys__memory__management.html',1,'']]]
];
