var searchData=
[
  ['calliope_20mini',['Calliope mini',['../group__boards__calliope-mini.html',1,'']]],
  ['cc2538dk',['CC2538DK',['../group__boards__cc2538dk.html',1,'']]],
  ['cc2650stk',['CC2650STK',['../group__boards__cc2650stk.html',1,'']]],
  ['chronos',['Chronos',['../group__boards__chronos.html',1,'']]],
  ['common_20board_20groups',['Common Board Groups',['../group__boards__common.html',1,'']]],
  ['common_20files_20of_20arduino_20zero_20and_20clones',['Common files of Arduino Zero and clones',['../group__boards__common__arduino__zero.html',1,'']]],
  ['cc2538_20configuration_20snippets',['cc2538 Configuration Snippets',['../group__boards__common__cc2538.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group__CC13x2__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group__CC2538__cmsis.html',1,'']]],
  ['compile_20time_20configurations',['Compile time configurations',['../group__config.html',1,'']]],
  ['common_20macros',['Common Macros',['../group__core__macros.html',1,'']]],
  ['condition_20variable',['Condition Variable',['../group__core__sync__cond.html',1,'']]],
  ['c_2b_2b11_20wrapper_20for_20riot',['C++11 wrapper for RIOT',['../group__cpp11-compat.html',1,'']]],
  ['cpu',['CPU',['../group__cpu.html',1,'']]],
  ['cc2538_20adc',['CC2538 ADC',['../group__cpu__cc2538__adc.html',1,'']]],
  ['cc2538_20general_2dpurpose_20i_2fo',['CC2538 General-Purpose I/O',['../group__cpu__cc2538__gpio.html',1,'']]],
  ['cc2538_20general_20purpose_20timer',['CC2538 General Purpose Timer',['../group__cpu__cc2538__gptimer.html',1,'']]],
  ['cc2538_20rf_20core_20interface',['CC2538 RF core interface',['../group__cpu__cc2538__rfcore.html',1,'']]],
  ['cc2538_20system_20control',['CC2538 System Control',['../group__cpu__cc2538__sysctrl.html',1,'']]],
  ['cc2538_20uart',['CC2538 UART',['../group__cpu__cc2538__uart.html',1,'']]],
  ['cc26xx_5fcc13xx_20common',['CC26xx_CC13xx common',['../group__cpu__cc26xx__cc13xx.html',1,'']]],
  ['cc26xx_5fcc13xx_20common',['CC26xx_CC13xx common',['../group__cpu__cc26xx__cc13xx__definitions.html',1,'']]],
  ['cpu_5fspecific_5fperipheral_5fmemory_5fmap',['Cpu_specific_Peripheral_memory_map',['../group__cpu__specific__Peripheral__memory__map.html',1,'']]],
  ['can_20drivers',['CAN Drivers',['../group__drivers__can.html',1,'']]],
  ['can_20transceiver_20interface',['CAN transceiver interface',['../group__drivers__can__trx.html',1,'']]],
  ['can_20device_20driver_20interface',['CAN device driver interface',['../group__drivers__candev.html',1,'']]],
  ['cc1100_2fcc1100e_2fcc1101_20sub_2dghz_20transceiver_20driver',['CC1100/CC1100e/CC1101 Sub-GHz transceiver driver',['../group__drivers__cc110x.html',1,'']]],
  ['cc1100_2fcc1100e_2fcc1101_20sub_2dghz_20transceiver_20driver_20compile_20configuration',['CC1100/CC1100e/CC1101 Sub-GHz transceiver driver compile configuration',['../group__drivers__cc110x__config.html',1,'']]],
  ['cc1100_2fcc1100e_2fcc1101_2fcc1200_20common_20code',['CC1100/CC1100e/CC1101/CC1200 common code',['../group__drivers__cc1xxx.html',1,'']]],
  ['cc2420_20radio_20driver',['CC2420 radio driver',['../group__drivers__cc2420.html',1,'']]],
  ['ccs_20811_20digital_20gas_20sensor',['CCS 811 digital gas sensor',['../group__drivers__ccs811.html',1,'']]],
  ['cr20a_20and_20kw2xd_20radio_20driver_20compile_20configuration',['CR20A and KW2xD radio driver compile configuration',['../group__drivers__kw2xrf__config.html',1,'']]],
  ['control_20on_2dboard_20leds',['Control on-board LEDs',['../group__drivers__led.html',1,'']]],
  ['can',['CAN',['../group__drivers__periph__can.html',1,'']]],
  ['cpuid',['CPUID',['../group__drivers__periph__cpuid.html',1,'']]],
  ['common_20peripheral_20initialization',['Common peripheral initialization',['../group__drivers__periph__init.html',1,'']]],
  ['coap_20defines',['CoAP defines',['../group__net__coap.html',1,'']]],
  ['coap_20compile_20configurations',['CoAP compile configurations',['../group__net__coap__conf.html',1,'']]],
  ['core_20rd_20endpoint_20and_20lookup_20client',['CoRE RD Endpoint and Lookup Client',['../group__net__cord.html',1,'']]],
  ['core_20rd_20common',['CoRE RD Common',['../group__net__cord__common.html',1,'']]],
  ['core_20rd_20endpoint_20and_20lookup_20client_20configuration',['CoRE RD Endpoint and Lookup Client Configuration',['../group__net__cord__config.html',1,'']]],
  ['core_20rd_20endpoint',['CoRE RD Endpoint',['../group__net__cord__ep.html',1,'']]],
  ['core_20rd_20endpoint_20standalone_20extension',['CoRE RD Endpoint Standalone Extension',['../group__net__cord__ep__standalone.html',1,'']]],
  ['core_20rd_20simple_20registration_20endpoint',['CoRE RD Simple Registration Endpoint',['../group__net__cord__epsim.html',1,'']]],
  ['csma_2fca_20helper',['CSMA/CA helper',['../group__net__csma__sender.html',1,'']]],
  ['csma_2fca_20helper_20compile_20configurations',['CSMA/CA helper compile configurations',['../group__net__csma__sender__conf.html',1,'']]],
  ['common_20mac_20module',['Common MAC module',['../group__net__gnrc__mac.html',1,'']]],
  ['callback_20extension',['Callback extension',['../group__net__gnrc__netapi__callbacks.html',1,'']]],
  ['contexts_20for_206lowpan_20address_20compression',['Contexts for 6LoWPAN address compression',['../group__net__gnrc__sixlowpan__ctx.html',1,'']]],
  ['c25519_20cryptographic_20library',['C25519 cryptographic library',['../group__pkg__c25519.html',1,'']]],
  ['cayenne_20low_20power_20payload_20_28lpp_29',['Cayenne Low Power Payload (LPP)',['../group__pkg__cayenne-lpp.html',1,'']]],
  ['cifra_20cryptographic_20library',['Cifra cryptographic library',['../group__pkg__cifra.html',1,'']]],
  ['cn_2dcbor',['cn-cbor',['../group__pkg__cn-cbor.html',1,'']]],
  ['cross_20platform_20fixed_20point_20maths_20library',['Cross platform fixed point maths library',['../group__pkg__libfixmath.html',1,'']]],
  ['connection_20state_20management_20for_20netif',['Connection State Management for netif',['../group__pkg__nimble__netif__conn.html',1,'']]],
  ['color_20graphics_20library_20for_20embedded_20systems',['Color graphics library for embedded systems',['../group__pkg__ucglib.html',1,'']]],
  ['c_2b_2b_20compatibility_20with_20c11_20atomics',['C++ compatibility with C11 atomics',['../group__sys__c11__atomics__cpp__compat.html',1,'']]],
  ['can_20_28controller_20area_20network_29',['CAN (Controller Area Network)',['../group__sys__can.html',1,'']]],
  ['common_20definitions',['Common definitions',['../group__sys__can__common.html',1,'']]],
  ['connection',['Connection',['../group__sys__can__conn.html',1,'']]],
  ['callback_20multiplexer',['Callback multiplexer',['../group__sys__cb__mux.html',1,'']]],
  ['checksum',['Checksum',['../group__sys__checksum.html',1,'']]],
  ['crc16_2dccitt',['CRC16-CCITT',['../group__sys__checksum__crc16__ccitt.html',1,'']]],
  ['crc_2d8',['CRC-8',['../group__sys__checksum__crc8.html',1,'']]],
  ['crc16_20_28lightweight_29',['CRC16 (lightweight)',['../group__sys__checksum__ucrc16.html',1,'']]],
  ['core_20link_20format',['CoRE Link Format',['../group__sys__clif.html',1,'']]],
  ['color',['Color',['../group__sys__color.html',1,'']]],
  ['crypto',['Crypto',['../group__sys__crypto.html',1,'']]],
  ['chacha20poly1305_20aead_20cipher',['chacha20poly1305 AEAD cipher',['../group__sys__crypto__chacha20poly1305.html',1,'']]],
  ['constfs_20static_20file_20system',['ConstFS static file system',['../group__sys__fs__constfs.html',1,'']]],
  ['colored_20log_20module',['Colored log module',['../group__sys__log__color.html',1,'']]],
  ['conversion_20using_20shifts',['conversion using shifts',['../group__sys__ztimer__convert__shift.html',1,'']]],
  ['cdc_20_2d_20usb_20communications_20device_20class',['CDC - USB communications device class',['../group__usb__cdc.html',1,'']]]
];
