var searchData=
[
  ['bluetooth_20low_20energy_20_28ble_29',['Bluetooth Low Energy (BLE)',['../group__ble.html',1,'']]],
  ['bluetil',['Bluetil',['../group__ble__bluetil.html',1,'']]],
  ['ble_20advertising_20data_20_28ad_29_20processing',['BLE Advertising Data (AD) Processing',['../group__ble__bluetil__ad.html',1,'']]],
  ['ble_20address_20helper',['BLE Address Helper',['../group__ble__bluetil__addr.html',1,'']]],
  ['boards',['Boards',['../group__boards.html',1,'']]],
  ['blackpill_20board',['Blackpill board',['../group__boards__blackpill.html',1,'']]],
  ['blackpill_20board_20_28128kib_20flash_20hack_20version_29',['Blackpill board (128KiB flash hack version)',['../group__boards__blackpill__128kib.html',1,'']]],
  ['bluepill_20board',['Bluepill board',['../group__boards__bluepill.html',1,'']]],
  ['bluepill_20board_20_28128kib_20flash_20hack_20version_29',['Bluepill board (128KiB flash hack version)',['../group__boards__bluepill__128kib.html',1,'']]],
  ['blackpill_20and_20bluepill_20common_20code',['Blackpill and Bluepill common code',['../group__boards__common__blxxxpill.html',1,'']]],
  ['board_20communication_20controller',['Board communication controller',['../group__boards__common__silabs__drivers__bc.html',1,'']]],
  ['bbc_20micro_3abit',['BBC micro:bit',['../group__boards__microbit.html',1,'']]],
  ['bh1750fvi_20light_20sensor',['BH1750FVI Light Sensor',['../group__drivers__bh1750fvi.html',1,'']]],
  ['bh1900nux_20temperature_20sensor',['BH1900NUX Temperature sensor',['../group__drivers__bh1900nux.html',1,'']]],
  ['bme680_20temperature_2fhumidity_2fpressure_2fgas_20sensor',['BME680 Temperature/Humidity/Pressure/Gas sensor',['../group__drivers__bme680.html',1,'']]],
  ['bmp180_20temperature_20and_20pressure_20sensor',['BMP180 temperature and pressure sensor',['../group__drivers__bmp180.html',1,'']]],
  ['bmx055_209_2daxis_20sensor',['BMX055 9-axis sensor',['../group__drivers__bmx055.html',1,'']]],
  ['bmx055_20sensor_20driver_20compile_20configuration',['BMX055 sensor driver compile configuration',['../group__drivers__bmx055__config.html',1,'']]],
  ['bmp280_2fbme280_20temperature_2c_20pressure_20and_20humidity_20sensor',['BMP280/BME280 temperature, pressure and humidity sensor',['../group__drivers__bmx280.html',1,'']]],
  ['bluetooth_20low_20energy_20drivers',['Bluetooth Low Energy drivers',['../group__nrf52832-ble.html',1,'']]],
  ['blake2_20hashing_20library',['BLAKE2 hashing library',['../group__pkg__libb2.html',1,'']]],
  ['base64_20encoder_20decoder',['base64 encoder decoder',['../group__sys__base64.html',1,'']]],
  ['binary_20coded_20decimal',['Binary coded decimal',['../group__sys__bcd.html',1,'']]],
  ['benchmark',['Benchmark',['../group__sys__benchmark.html',1,'']]],
  ['bitfields',['Bitfields',['../group__sys__bitfield.html',1,'']]],
  ['bloom_20filter',['Bloom filter',['../group__sys__bloom.html',1,'']]],
  ['bernstein_20hash_20djb2',['Bernstein hash djb2',['../group__sys__hashes__djb2.html',1,'']]],
  ['board_20reset_20via_20usb_20cdc_20acm',['Board reset via USB CDC ACM',['../group__sys__usb__board__reset.html',1,'']]]
];
