var searchData=
[
  ['generic_20ble_20defines',['Generic BLE defines',['../group__ble__defs.html',1,'']]],
  ['generic_20esp32_2dwroom_2d32_20boards',['Generic ESP32-WROOM-32 boards',['../group__boards__esp32__wroom-32.html',1,'']]],
  ['grove_20ledbar',['Grove ledbar',['../group__drivers__grove__ledbar.html',1,'']]],
  ['gnrc_20adapter_20for_20nrfmin',['GNRC adapter for nrfmin',['../group__drivers__nrf5x__nrfmin__gnrc.html',1,'']]],
  ['gpio',['GPIO',['../group__drivers__periph__gpio.html',1,'']]],
  ['gpio_20i_2fo_20utils',['GPIO I/O Utils',['../group__gpio__util.html',1,'']]],
  ['gcoap',['Gcoap',['../group__net__gcoap.html',1,'']]],
  ['gcoap_20compile_20configurations',['Gcoap compile configurations',['../group__net__gcoap__conf.html',1,'']]],
  ['generic_20_28gnrc_29_20network_20stack',['Generic (GNRC) network stack',['../group__net__gnrc.html',1,'']]],
  ['gnrc_20compile_20configurations',['GNRC compile configurations',['../group__net__gnrc__conf.html',1,'']]],
  ['gomach',['GoMacH',['../group__net__gnrc__gomach.html',1,'']]],
  ['gnrc_20gomach_20compile_20configuration',['GNRC GoMacH compile configuration',['../group__net__gnrc__gomach__conf.html',1,'']]],
  ['gnrc_20ipv6_20address_20blacklisting_20compile_20configurations',['GNRC IPv6 address blacklisting compile configurations',['../group__net__gnrc__ipv6__blacklist__conf.html',1,'']]],
  ['gnrc_20ipv6_20compile_20configurations',['GNRC IPv6 compile configurations',['../group__net__gnrc__ipv6__conf.html',1,'']]],
  ['gnrc_20ipv6_20extension_20header_20compile_20configurations',['GNRC IPv6 extension header compile configurations',['../group__net__gnrc__ipv6__ext__conf.html',1,'']]],
  ['gnrc_20ipv6_20nib_20compile_20configurations',['GNRC IPv6 NIB compile configurations',['../group__net__gnrc__ipv6__nib__conf.html',1,'']]],
  ['gnrc_20ipv6_20address_20whitelisting_20compile_20configurations',['GNRC IPv6 address whitelisting compile configurations',['../group__net__gnrc__ipv6__whitelist__conf.html',1,'']]],
  ['gnrc_20lorawan',['GNRC LoRaWAN',['../group__net__gnrc__lorawan.html',1,'']]],
  ['gnrc_20lorawan_20compile_20configurations',['GNRC LoRaWAN compile configurations',['../group__net__gnrc__lorawan__conf.html',1,'']]],
  ['gnrc_20lwmac_20compile_20configurations',['GNRC LWMAC compile configurations',['../group__net__gnrc__lwmac__conf.html',1,'']]],
  ['gnrc_20mac_20compile_20configurations',['GNRC MAC compile configurations',['../group__net__gnrc__mac__conf.html',1,'']]],
  ['gnrc_20communication_20interface',['GNRC communication interface',['../group__net__gnrc__netapi.html',1,'']]],
  ['gnrc_20network_20interface_20configurations',['GNRC network interface configurations',['../group__net__gnrc__netif__conf.html',1,'']]],
  ['generic_20network_20interface_20header',['Generic network interface header',['../group__net__gnrc__netif__hdr.html',1,'']]],
  ['gnrc_20netapi_20test_20compile_20configurations',['GNRC NETAPI test compile configurations',['../group__net__gnrc__nettest__conf.html',1,'']]],
  ['gnrc_20pktbuf_20compile_20configurations',['GNRC PKTBUF compile configurations',['../group__net__gnrc__pktbuf__conf.html',1,'']]],
  ['gnrc_20pktdump_20compile_20configurations',['GNRC PKTDUMP compile configurations',['../group__net__gnrc__pktdump__conf.html',1,'']]],
  ['gnrc_206lowpan_20compile_20configurations',['GNRC 6LoWPAN compile configurations',['../group__net__gnrc__sixlowpan__config.html',1,'']]],
  ['gnrc_2dspecific_20implementation_20of_20the_20sock_20api',['GNRC-specific implementation of the sock API',['../group__net__gnrc__sock.html',1,'']]],
  ['gnrc_20sock_20implementation_20compile_20configurations',['GNRC sock implementation compile configurations',['../group__net__gnrc__sock__conf.html',1,'']]],
  ['gnrc_20tcp_20compile_20configurations',['GNRC TCP compile configurations',['../group__net__gnrc__tcp__conf.html',1,'']]],
  ['gnrc_20udp_20compile_20configurations',['GNRC UDP compile configurations',['../group__net__gnrc__udp__conf.html',1,'']]],
  ['gemm_20_28general_20matrix_20multiplication_29_20library',['GEMM (General Matrix Multiplication) library',['../group__pkg__gemmlowp.html',1,'']]],
  ['gps_20parser_20library',['GPS parser library',['../group__pkg__minmea.html',1,'']]],
  ['gnrc_20netif_20implementation',['GNRC netif Implementation',['../group__pkg__nimble__netif.html',1,'']]],
  ['gnrc_20netif_20drivers_20auto_2dinitialization',['GNRC netif drivers auto-initialization',['../group__sys__auto__init__gnrc__netif.html',1,'']]]
];
