var searchData=
[
  ['limifrog_20version_201',['LimiFrog Version 1',['../group__boards__limifrog-v1.html',1,'']]],
  ['lobaro_20lorabox',['Lobaro Lorabox',['../group__boards__lobaro__lorabox.html',1,'']]],
  ['lm4f',['LM4F',['../group__cpu__lm4f120.html',1,'']]],
  ['l3g4200d_20gyroscope',['L3G4200D gyroscope',['../group__drivers__l3g4200d.html',1,'']]],
  ['l3g4200d_20gyroscope_20driver_20compile_20configuration',['L3G4200D gyroscope driver compile configuration',['../group__drivers__l3g4200d__config.html',1,'']]],
  ['lc709203f',['LC709203F',['../group__drivers__lc709203f.html',1,'']]],
  ['lis2dh12_20accelerometer',['LIS2DH12 Accelerometer',['../group__drivers__lis2dh12.html',1,'']]],
  ['lis3dh_20accelerometer',['LIS3DH accelerometer',['../group__drivers__lis3dh.html',1,'']]],
  ['lis3mdl_203_2daxis_20magnetometer',['LIS3MDL 3-axis magnetometer',['../group__drivers__lis3mdl.html',1,'']]],
  ['lpd8808_20based_20led_20strip',['LPD8808 based LED Strip',['../group__drivers__lpd8808.html',1,'']]],
  ['lps331ap_2flps25hb_2flps22hb_20pressure_20sensors_20driver',['LPS331AP/LPS25HB/LPS22HB Pressure Sensors Driver',['../group__drivers__lpsxxx.html',1,'']]],
  ['lps331ap_2flps25hb_2flps22hb_20driver_20compile_20configuration',['LPS331AP/LPS25HB/LPS22HB driver compile configuration',['../group__drivers__lpsxxx__config.html',1,'']]],
  ['lsm303dlhc_203d_20accelerometer_2fmagnetometer',['LSM303DLHC 3D accelerometer/magnetometer',['../group__drivers__lsm303dlhc.html',1,'']]],
  ['lsm6dsl_203d_20accelerometer_2fgyroscope',['LSM6DSL 3D accelerometer/gyroscope',['../group__drivers__lsm6dsl.html',1,'']]],
  ['ltc4150_20coulomb_20counter',['LTC4150 coulomb counter',['../group__drivers__ltc4150.html',1,'']]],
  ['lora_20drivers',['LoRa drivers',['../group__drivers__netdev__lora.html',1,'']]],
  ['linux_20user_20mode_20spi_20driver',['Linux User Mode SPI Driver',['../group__drivers__spidev__linux.html',1,'']]],
  ['lwm2m_20client_20using_20wakaama',['LwM2M Client using Wakaama',['../group__lwm2m__client.html',1,'']]],
  ['lwm2m_20object_20implementations',['LwM2M Object implementations',['../group__lwm2m__objects.html',1,'']]],
  ['lwmac',['LWMAC',['../group__net__gnrc__lwmac.html',1,'']]],
  ['link_2dlayer_20broadcast_20deduplication',['Link-layer Broadcast deduplication',['../group__net__gnrc__netif__dedup.html',1,'']]],
  ['link_20layer_20address_20filter',['Link layer address filter',['../group__net__l2filter.html',1,'']]],
  ['lora_20modulation',['LoRa modulation',['../group__net__lora.html',1,'']]],
  ['lora_20modulation_20compile_20configurations',['LoRa modulation compile configurations',['../group__net__lora__conf.html',1,'']]],
  ['loramac',['LoRaMAC',['../group__net__loramac.html',1,'']]],
  ['loramac_20compile_20configurations',['LoRaMAC compile configurations',['../group__net__loramac__conf.html',1,'']]],
  ['lorawan',['LoRaWAN',['../group__net__lorawan.html',1,'']]],
  ['lorawan_20header',['LoRaWAN header',['../group__net__lorawan__hdr.html',1,'']]],
  ['lightweight_20compression_20library',['Lightweight compression library',['../group__pkg__heatshrink.html',1,'']]],
  ['libcose_20for_20riot',['libcose for RIOT',['../group__pkg__libcose.html',1,'']]],
  ['libhydrogen_20cryptographic_20library',['LibHydrogen cryptographic library',['../group__pkg__libhydrogen.html',1,'']]],
  ['littlefs_20file_20system',['littlefs file system',['../group__pkg__littlefs.html',1,'']]],
  ['littlefs_20v2_2ex_2ey_20file_20system',['littlefs v2.x.y file system',['../group__pkg__littlefs2.html',1,'']]],
  ['lora_20serialization',['Lora Serialization',['../group__pkg__lora-serialization.html',1,'']]],
  ['lua_20ported_20to_20riot',['Lua ported to RIOT',['../group__pkg__lua.html',1,'']]],
  ['littlevgl_20_2d_20open_2dsource_20embedded_20gui_20library',['LittlevGL - Open-Source Embedded GUI Library',['../group__pkg__lvgl.html',1,'']]],
  ['lwip_20network_20stack',['lwIP network stack',['../group__pkg__lwip.html',1,'']]],
  ['lwip_20netdev_20adapter',['lwIP netdev adapter',['../group__pkg__lwip__netdev.html',1,'']]],
  ['lwip_20options',['lwIP options',['../group__pkg__lwip__opts.html',1,'']]],
  ['lwip_2dspecific_20implementation_20of_20sock_20api',['lwIP-specific implementation of sock API',['../group__pkg__lwip__sock.html',1,'']]],
  ['lightweight_20asn_2e1_20decoding_2fencoding_20library',['Lightweight ASN.1 decoding/encoding library',['../group__pkg__tiny-asn1.html',1,'']]],
  ['lightweight_20morse_20encoder',['Lightweight Morse encoder',['../group__pkg__umorse.html',1,'']]],
  ['littlefs_20integration',['littlefs integration',['../group__sys__littlefs.html',1,'']]],
  ['littlefs_20v2_20integration',['littlefs v2 integration',['../group__sys__littlefs2.html',1,'']]],
  ['locally_20unique_20id_20generator',['Locally Unique ID Generator',['../group__sys__luid.html',1,'']]],
  ['layered_20pm_20infrastructure',['Layered PM Infrastructure',['../group__sys__pm__layered.html',1,'']]]
];
