var group__boards =
[
    [ "ACD52832", "group__boards__acd52832.html", "group__boards__acd52832" ],
    [ "ATmega common", "group__boards__common__atmega.html", null ],
    [ "Adafruit Clue", "group__boards__adafruit-clue.html", "group__boards__adafruit-clue" ],
    [ "Adafruit Feather M0", "group__boards__feather-m0.html", "group__boards__feather-m0" ],
    [ "Adafruit Feather nRF52840 Express", "group__boards__feather-nrf52840.html", "group__boards__feather-nrf52840" ],
    [ "Airfy Beacon", "group__boards__airfy-beacon.html", "group__boards__airfy-beacon" ],
    [ "Arduino Due", "group__boards__arduino-due.html", null ],
    [ "Arduino Duemilanove", "group__boards__arduino-duemilanove.html", "group__boards__arduino-duemilanove" ],
    [ "Arduino Leonardo", "group__boards__arduino-leonardo.html", "group__boards__arduino-leonardo" ],
    [ "Arduino MKR WAN 1300", "group__boards__arduino-mkrwan1300.html", "group__boards__arduino-mkrwan1300" ],
    [ "Arduino MKR1000", "group__boards__arduino-mkr1000.html", "group__boards__arduino-mkr1000" ],
    [ "Arduino MKRFOX1200", "group__boards__arduino-mkrfox1200.html", "group__boards__arduino-mkrfox1200" ],
    [ "Arduino MKRZERO", "group__boards__arduino-mkrzero.html", "group__boards__arduino-mkrzero" ],
    [ "Arduino Mega 2560", "group__boards__arduino-mega2560.html", "group__boards__arduino-mega2560" ],
    [ "Arduino Nano", "group__boards__arduino-nano.html", "group__boards__arduino-nano" ],
    [ "Arduino Nano 33 BLE", "group__boards__arduino-nano-33-ble.html", "group__boards__arduino-nano-33-ble" ],
    [ "Arduino Uno", "group__boards__arduino-uno.html", "group__boards__arduino-uno" ],
    [ "Arduino Zero", "group__boards__arduino-zero.html", null ],
    [ "Atmega256RFR2 Xplained Pro", "group__boards__atmega256rfr2-xpro.html", "group__boards__atmega256rfr2-xpro" ],
    [ "Atmega256RFR2 rss2", "group__boards__avr-rss2.html", "group__boards__avr-rss2" ],
    [ "Atmel SAM D21 Xplained Pro", "group__boards__samd21-xpro.html", "group__boards__samd21-xpro" ],
    [ "Atmel SAM L21 Xplained Pro", "group__boards__saml21-xpro.html", "group__boards__saml21-xpro" ],
    [ "Atmel SAM R21 Xplained Pro", "group__boards__samr21-xpro.html", "group__boards__samr21-xpro" ],
    [ "Atmel SAM R30 Xplained Pro", "group__boards__samr30-xpro.html", "group__boards__samr30-xpro" ],
    [ "Avsextrem", "group__boards__avsextrem.html", "group__boards__avsextrem" ],
    [ "BBC micro:bit", "group__boards__microbit.html", "group__boards__microbit" ],
    [ "Blackpill board", "group__boards__blackpill.html", "group__boards__blackpill" ],
    [ "Blackpill board (128KiB flash hack version)", "group__boards__blackpill__128kib.html", "group__boards__blackpill__128kib" ],
    [ "Bluepill board", "group__boards__bluepill.html", "group__boards__bluepill" ],
    [ "Bluepill board (128KiB flash hack version)", "group__boards__bluepill__128kib.html", "group__boards__bluepill__128kib" ],
    [ "CC2538DK", "group__boards__cc2538dk.html", "group__boards__cc2538dk" ],
    [ "CC2650STK", "group__boards__cc2650stk.html", "group__boards__cc2650stk" ],
    [ "Calliope mini", "group__boards__calliope-mini.html", "group__boards__calliope-mini" ],
    [ "Chronos", "group__boards__chronos.html", "group__boards__chronos" ],
    [ "Common Board Groups", "group__boards__common.html", "group__boards__common" ],
    [ "Decawave DWM1001", "group__boards__dwm1001.html", "group__boards__dwm1001" ],
    [ "Digilent PIC32 WiFire", "group__boards__pic32-wifire.html", "group__boards__pic32-wifire" ],
    [ "Dragino LSN50 LoRa Sensor Node", "group__boards__lsn50.html", "group__boards__lsn50" ],
    [ "EK-LM4F120XL", "group__boards__ek-lm4f120xl.html", "group__boards__ek-lm4f120xl" ],
    [ "ESP32 Boards", "group__boards__esp32.html", "group__boards__esp32" ],
    [ "ESP8266 Boards", "group__boards__esp8266.html", "group__boards__esp8266" ],
    [ "Eistec Mulle", "group__boards__mulle.html", "group__boards__mulle" ],
    [ "F4VI1", "group__boards__f4vi1.html", "group__boards__f4vi1" ],
    [ "Firefly Board", "group__boards__firefly.html", "group__boards__firefly" ],
    [ "Freescale FRDM-KW41Z Board", "group__boards__frdm-kw41z.html", "group__boards__frdm-kw41z" ],
    [ "HamiltonIoT Hamilton", "group__boards__hamilton.html", "group__boards__hamilton" ],
    [ "IKEA TRÅDFRI modules", "group__boards__ikea-tradfri.html", "group__boards__ikea-tradfri" ],
    [ "IoT-LAB A8 M3 open node", "group__boards__iotlab-a8-m3.html", "group__boards__iotlab-a8-m3" ],
    [ "IoT-LAB M3 open node", "group__boards__iotlab-m3.html", "group__boards__iotlab-m3" ],
    [ "LimiFrog Version 1", "group__boards__limifrog-v1.html", "group__boards__limifrog-v1" ],
    [ "Lobaro Lorabox", "group__boards__lobaro__lorabox.html", "group__boards__lobaro__lorabox" ],
    [ "MCB2388 Evaluation Board", "group__boards__mcb2388.html", "group__boards__mcb2388" ],
    [ "MSB-430", "group__boards__msb430.html", "group__boards__msb430" ],
    [ "MSB-430H", "group__boards__msb430h.html", "group__boards__msb430h" ],
    [ "MSB-A2", "group__boards__msba2.html", "group__boards__msba2" ],
    [ "MSB-IoT", "group__boards__msbiot.html", "group__boards__msbiot" ],
    [ "Mega1284P-Xplained", "group__boards__mega-xplained.html", "group__boards__mega-xplained" ],
    [ "Microchip SAM E54 Xplained Pro", "group__boards__same54-xpro.html", "group__boards__same54-xpro" ],
    [ "Microchip SAM R34 Xplained Pro", "group__boards__samr34-xpro.html", "group__boards__samr34-xpro" ],
    [ "Microchip SAML10 Xplained Pro", "group__boards__saml10-xpro.html", null ],
    [ "Microchip SAML11 Xplained Pro", "group__boards__saml11-xpro.html", null ],
    [ "Microchip SAML1X", "group__boards__common__saml1x.html", "group__boards__common__saml1x" ],
    [ "Microduino CoreRF", "group__boards__microduino-corerf.html", "group__boards__microduino-corerf" ],
    [ "MikroE 6LoWPAN Clicker", "group__boards__6lowpan-clicker.html", "group__boards__6lowpan-clicker" ],
    [ "NRF6310 (Nordic NRF Hardware Development Kit)", "group__boards__nrf6310.html", "group__boards__nrf6310" ],
    [ "NXP FRDM-K22F Board", "group__boards__frdm-k22f.html", "group__boards__frdm-k22f" ],
    [ "NXP FRDM-K64F Board", "group__boards__frdm-k64f.html", "group__boards__frdm-k64f" ],
    [ "NXP USB-KW41Z Board", "group__boards__usb-kw41z.html", "group__boards__usb-kw41z" ],
    [ "NZ32-SC151", "group__boards__nz32-sc151.html", "group__boards__nz32-sc151" ],
    [ "Native Board", "group__boards__native.html", "group__boards__native" ],
    [ "Nordic Thingy:52", "group__boards__thingy52.html", "group__boards__thingy52" ],
    [ "OpenCM9.04", "group__boards__opencm904.html", "group__boards__opencm904" ],
    [ "OpenMote-b", "group__boards__openmote-b.html", "group__boards__openmote-b" ],
    [ "OpenMote-cc2538", "group__boards__openmote-cc2538.html", "group__boards__openmote-cc2538" ],
    [ "Particle Argon", "group__boards__particle-argon.html", "group__boards__particle-argon" ],
    [ "Particle Boron", "group__boards__particle-boron.html", "group__boards__particle-boron" ],
    [ "Particle Mesh common", "group__boards__common__particle-mesh.html", "group__boards__common__particle-mesh" ],
    [ "Particle Xenon", "group__boards__particle-xenon.html", "group__boards__particle-xenon" ],
    [ "PhyNODE KW41Z", "group__boards__phynode-kw41z.html", "group__boards__phynode-kw41z" ],
    [ "Phytec reel board", "group__boards__reel.html", "group__boards__reel" ],
    [ "PineTime", "group__boards__pinetime.html", "group__boards__pinetime" ],
    [ "RE-Mote Prototype A", "group__boards__remote-pa.html", "group__boards__remote-pa" ],
    [ "RE-Mote Revision A", "group__boards__remote-reva.html", "group__boards__remote-reva" ],
    [ "RE-Mote Revision B", "group__boards__remote-revb.html", "group__boards__remote-revb" ],
    [ "RuuviTag", "group__boards__ruuvitag.html", "group__boards__ruuvitag" ],
    [ "SODAQ Autonomo", "group__boards__sodaq-autonomo.html", "group__boards__sodaq-autonomo" ],
    [ "SODAQ ExpLoRer", "group__boards__sodaq-explorer.html", "group__boards__sodaq-explorer" ],
    [ "SODAQ ONE", "group__boards__sodaq-one.html", "group__boards__sodaq-one" ],
    [ "SODAQ SARA AFF", "group__boards__sodaq-sara-aff.html", "group__boards__sodaq-sara-aff" ],
    [ "SODAQ SARA SFF", "group__boards__sodaq-sara-sff.html", "group__boards__sodaq-sara-sff" ],
    [ "ST B-L072Z-LRWAN1 LoRa discovery", "group__boards__b-l072z-lrwan1.html", "group__boards__b-l072z-lrwan1" ],
    [ "ST B-L475E-IOT01A", "group__boards__b-l475e-iot01a.html", "group__boards__b-l475e-iot01a" ],
    [ "ST I-NUCLEO-LRWAN1 LoRa board", "group__boards__i-nucleo-lrwan1.html", "group__boards__i-nucleo-lrwan1" ],
    [ "ST P-L496G-CELL02", "group__boards__p-l496g-cell02.html", "group__boards__p-l496g-cell02" ],
    [ "STM32 Nucleo-144", "group__boards__common__nucleo144.html", "group__boards__common__nucleo144" ],
    [ "STM32 Nucleo-32", "group__boards__common__nucleo32.html", "group__boards__common__nucleo32" ],
    [ "STM32 Nucleo-64", "group__boards__common__nucleo64.html", "group__boards__common__nucleo64" ],
    [ "STM32 Olimexino-stm32", "group__boards__olimexino-stm32.html", "group__boards__olimexino-stm32" ],
    [ "STM32F030F4 Demo Board", "group__boards__stm32f030f4-demo.html", "group__boards__stm32f030f4-demo" ],
    [ "STM32F0Discovery", "group__boards__stm32f0discovery.html", "group__boards__stm32f0discovery" ],
    [ "STM32F3Discovery", "group__boards__stm32f3discovery.html", "group__boards__stm32f3discovery" ],
    [ "STM32F429I-DISC1", "group__boards__stm32f429i-disc1.html", "group__boards__stm32f429i-disc1" ],
    [ "STM32F429I-DISCO", "group__boards__stm32f429i-disco.html", null ],
    [ "STM32F4Discovery", "group__boards__stm32f4discovery.html", "group__boards__stm32f4discovery" ],
    [ "STM32F723E-DISCO board", "group__boards__stm32f723e-disco.html", "group__boards__stm32f723e-disco" ],
    [ "STM32F769I-DISCO board", "group__boards__stm32f769i-disco.html", "group__boards__stm32f769i-disco" ],
    [ "STM32L0538-DISCO", "group__boards__stm32l0538-disco.html", "group__boards__stm32l0538-disco" ],
    [ "STM32L476G-DISCO", "group__boards__stm32l476g-disco.html", "group__boards__stm32l476g-disco" ],
    [ "Seeeduino Arch Pro development kit", "group__boards__seeduino__arch-pro.html", "group__boards__seeduino__arch-pro" ],
    [ "SenseBox MCU with SAMD21", "group__boards__sensebox__samd21.html", "group__boards__sensebox__samd21" ],
    [ "Serpente R2", "group__boards__serpente.html", "group__boards__serpente" ],
    [ "SiFive HiFive1 RISC-V board", "group__boards__hifive1.html", "group__boards__hifive1" ],
    [ "SiFive HiFive1b RISC-V board", "group__boards__hifive1b.html", "group__boards__hifive1b" ],
    [ "Silicon Labs SLSTK3401A starter kit", "group__boards__slstk3401a.html", "group__boards__slstk3401a" ],
    [ "Silicon Labs SLSTK3402A starter kit", "group__boards__slstk3402a.html", "group__boards__slstk3402a" ],
    [ "Silicon Labs SLTB001A starter kit", "group__boards__sltb001a.html", "group__boards__sltb001a" ],
    [ "Silicon Labs SLWSTK6000B starter kit", "group__boards__common__slwstk6000b.html", "group__boards__common__slwstk6000b" ],
    [ "Silicon Labs STK3600 starter kit", "group__boards__stk3600.html", "group__boards__stk3600" ],
    [ "Silicon Labs STK3700 starter kit", "group__boards__stk3700.html", "group__boards__stk3700" ],
    [ "Silicon Labs WSTK6220 Eval Kit", "group__boards__slwstk6220a.html", "group__boards__slwstk6220a" ],
    [ "Spark-Core", "group__boards__spark-core.html", "group__boards__spark-core" ],
    [ "Standalone ATmega1284P", "group__boards__atmega1284p.html", "group__boards__atmega1284p" ],
    [ "Standalone ATmega328p", "group__boards__atmega328p.html", "group__boards__atmega328p" ],
    [ "TI CC1312 LaunchPad", "group__boards__cc1312__launchpad.html", "group__boards__cc1312__launchpad" ],
    [ "TI CC1352 LaunchPad", "group__boards__cc1352__launchpad.html", "group__boards__cc1352__launchpad" ],
    [ "TI CC1352P LaunchPad", "group__boards__cc1352p__launchpad.html", "group__boards__cc1352p__launchpad" ],
    [ "TI CC2650 LaunchPad XL", "group__boards__cc2650__launchpad.html", "group__boards__cc2650__launchpad" ],
    [ "Teensy3.1 & 3.2", "group__boards__teensy31.html", "group__boards__teensy31" ],
    [ "TelosB", "group__boards__telosb.html", "group__boards__telosb" ],
    [ "UDOO", "group__boards__udoo.html", null ],
    [ "Ublox C030-U201", "group__boards__ublox-c030-u201.html", "group__boards__ublox-c030-u201" ],
    [ "WSN430 v1.3b", "group__boards__wsn430-v1__3b.html", "group__boards__wsn430-v1__3b" ],
    [ "WSN430 v1.4", "group__boards__wsn430-v1__4.html", "group__boards__wsn430-v1__4" ],
    [ "Waspmote PRO v1.2", "group__boards__waspmote-pro.html", "group__boards__waspmote-pro" ],
    [ "WeAct-F411CE board", "group__boards__weact-f411ce.html", "group__boards__weact-f411ce" ],
    [ "WeMos Arduino Zero Clone", "group__boards__wemos-zero.html", null ],
    [ "Yunjia NRF51822", "group__boards__yunjia-nrf51822.html", "group__boards__yunjia-nrf51822" ],
    [ "Zolertia Z1", "group__boards__z1.html", "group__boards__z1" ],
    [ "deRFmega128 modules from Dresden Elektronik", "group__boards__deRFmega128.html", "group__boards__deRFmega128" ],
    [ "deRFmega256 modules from Dresden Elektronik", "group__boards__deRFmega256.html", "group__boards__deRFmega256" ],
    [ "fox", "group__boards__fox.html", "group__boards__fox" ],
    [ "im880b", "group__boards__im880b.html", "group__boards__im880b" ],
    [ "maple-mini", "group__boards__maple-mini.html", "group__boards__maple-mini" ],
    [ "mbed LPC1768 development kit", "group__boards__mbed__lpc1768.html", "group__boards__mbed__lpc1768" ],
    [ "nRF51 Dongle", "group__boards__nrf51dongle.html", "group__boards__nrf51dongle" ],
    [ "nRF51DK Development Kit", "group__boards__nrf51dk.html", "group__boards__nrf51dk" ],
    [ "nRF52 DK", "group__boards__nrf52dk.html", "group__boards__nrf52dk" ],
    [ "nRF52832-MDK", "group__boards__nrf52832-mdk.html", "group__boards__nrf52832-mdk" ],
    [ "nRF52840 DK", "group__boards__nrf52840dk.html", "group__boards__nrf52840dk" ],
    [ "nRF52840-Dongle", "group__boards__nrf52840dongle.html", "group__boards__nrf52840dongle" ],
    [ "nRF52840-MDK", "group__boards__nrf52840-mdk.html", "group__boards__nrf52840-mdk" ],
    [ "openlabs.co kw41z-mini board", "group__boards__openlabs-kw41z-mini.html", "group__boards__openlabs-kw41z-mini" ],
    [ "openlabs.co kw41z-mini-256kib board", "group__boards__openlabs-kw41z-mini-256kib.html", null ],
    [ "phyWAVE-KW22 Board", "group__boards__pba-d-01-kw2x.html", "group__boards__pba-d-01-kw2x" ],
    [ "pyboard", "group__boards__pyboard.html", "group__boards__pyboard" ]
];