var group__drivers__sensors =
[
    [ "AD7746 Capacitance-to-digital converter driver", "group__drivers__ad7746.html", "group__drivers__ad7746" ],
    [ "ADCXX1C ADC device driver", "group__drivers__adcxx1c.html", "group__drivers__adcxx1c" ],
    [ "ADS101x/111x ADC device driver", "group__drivers__ads101x.html", "group__drivers__ads101x" ],
    [ "ADT7310 SPI temperature sensor", "group__drivers__adt7310.html", "group__drivers__adt7310" ],
    [ "ADXL345 3-Axis accelerometer", "group__drivers__adxl345.html", "group__drivers__adxl345" ],
    [ "APDS99XX proximity and ambient light sensors", "group__drivers__apds99xx.html", "group__drivers__apds99xx" ],
    [ "AT30TSE75x temperature sensor with EEPROM", "group__drivers__at30tse75x.html", "group__drivers__at30tse75x" ],
    [ "Adafruit Seesaw Soil Moisture and Temperature Sensor", "group__drivers__seesaw__soil.html", "group__drivers__seesaw__soil" ],
    [ "Atmel IO1 Xplained Extension board", "group__drivers__io1__xplained.html", "group__drivers__io1__xplained" ],
    [ "BH1750FVI Light Sensor", "group__drivers__bh1750fvi.html", "group__drivers__bh1750fvi" ],
    [ "BH1900NUX Temperature sensor", "group__drivers__bh1900nux.html", "group__drivers__bh1900nux" ],
    [ "BME680 Temperature/Humidity/Pressure/Gas sensor", "group__drivers__bme680.html", "group__drivers__bme680" ],
    [ "BMP180 temperature and pressure sensor", "group__drivers__bmp180.html", "group__drivers__bmp180" ],
    [ "BMP280/BME280 temperature, pressure and humidity sensor", "group__drivers__bmx280.html", "group__drivers__bmx280" ],
    [ "BMX055 9-axis sensor", "group__drivers__bmx055.html", "group__drivers__bmx055" ],
    [ "CCS 811 digital gas sensor", "group__drivers__ccs811.html", "group__drivers__ccs811" ],
    [ "DCF77 long wave receiver with 77,5 kHz", "group__drivers__dcf77.html", "group__drivers__dcf77" ],
    [ "DHT Family of Humidity and Temperature Sensors", "group__drivers__dht.html", "group__drivers__dht" ],
    [ "DS1307 RTC", "group__drivers__ds1307.html", "group__drivers__ds1307" ],
    [ "DS18 temperature sensor driver", "group__drivers__ds18.html", "group__drivers__ds18" ],
    [ "DS3231 Real Time Clock", "group__drivers__ds3231.html", "group__drivers__ds3231" ],
    [ "DS3234 Extremely Accurate SPI RTC", "group__drivers__ds3234.html", "group__drivers__ds3234" ],
    [ "FXOS8700 3-axis accelerometer/magnetometer", "group__drivers__fxos8700.html", "group__drivers__fxos8700" ],
    [ "GP2Y10xx Optical Dust Sensor device driver", "group__drivers__gp2y10xx.html", "group__drivers__gp2y10xx" ],
    [ "HDC1000 Humidity and Temperature Sensor", "group__drivers__hdc1000.html", "group__drivers__hdc1000" ],
    [ "HIH6130 humidity and temperature sensor", "group__drivers__hih6130.html", "group__drivers__hih6130" ],
    [ "HMC5883L 3-axis digital compass", "group__drivers__hmc5883l.html", "group__drivers__hmc5883l" ],
    [ "INA2XX current/power monitor", "group__drivers__ina2xx.html", "group__drivers__ina2xx" ],
    [ "INA3221 current/power monitor", "group__drivers__ina3221.html", "group__drivers__ina3221" ],
    [ "ISL29020 light sensor", "group__drivers__isl29020.html", "group__drivers__isl29020" ],
    [ "ISL29125 RGB light sensor", "group__drivers__isl29125.html", "group__drivers__isl29125" ],
    [ "ITG320X 3-axis gyroscope", "group__drivers__itg320x.html", "group__drivers__itg320x" ],
    [ "JC42 compliant temperature sensor driver", "group__drivers__jc42.html", "group__drivers__jc42" ],
    [ "L3G4200D gyroscope", "group__drivers__l3g4200d.html", "group__drivers__l3g4200d" ],
    [ "LC709203F", "group__drivers__lc709203f.html", "group__drivers__lc709203f" ],
    [ "LIS2DH12 Accelerometer", "group__drivers__lis2dh12.html", "group__drivers__lis2dh12" ],
    [ "LIS3DH accelerometer", "group__drivers__lis3dh.html", "group__drivers__lis3dh" ],
    [ "LIS3MDL 3-axis magnetometer", "group__drivers__lis3mdl.html", "group__drivers__lis3mdl" ],
    [ "LPS331AP/LPS25HB/LPS22HB Pressure Sensors Driver", "group__drivers__lpsxxx.html", "group__drivers__lpsxxx" ],
    [ "LSM303DLHC 3D accelerometer/magnetometer", "group__drivers__lsm303dlhc.html", "group__drivers__lsm303dlhc" ],
    [ "LSM6DSL 3D accelerometer/gyroscope", "group__drivers__lsm6dsl.html", "group__drivers__lsm6dsl" ],
    [ "LTC4150 coulomb counter", "group__drivers__ltc4150.html", "group__drivers__ltc4150" ],
    [ "MAG3110 3-Axis Digital Magnetometer", "group__drivers__mag3110.html", "group__drivers__mag3110" ],
    [ "MH-Z19 CO2 sensor", "group__drivers__mhz19.html", "group__drivers__mhz19" ],
    [ "MMA7660 Accelerometer", "group__drivers__mma7660.html", "group__drivers__mma7660" ],
    [ "MMA8x5x Accelerometer", "group__drivers__mma8x5x.html", "group__drivers__mma8x5x" ],
    [ "MPL3115A2 Pressure Sensor", "group__drivers__mpl3115a2.html", "group__drivers__mpl3115a2" ],
    [ "MPU-9X50 (MPU9150 and MPU9250) accelerometer/magnetometer/gyroscope", "group__drivers__mpu9x50.html", "group__drivers__mpu9x50" ],
    [ "MQ-3 Alcohol Tester", "group__drivers__mq3.html", "group__drivers__mq3" ],
    [ "Maxim DS75LX temperature sensor", "group__drivers__ds75lx.html", "group__drivers__ds75lx" ],
    [ "OPT3001 Ambient Light Sensor", "group__drivers__opt3001.html", "group__drivers__opt3001" ],
    [ "PIR Motion Sensor", "group__drivers__pir.html", "group__drivers__pir" ],
    [ "Pulse counter", "group__drivers__pulse__counter.html", "group__drivers__pulse__counter" ],
    [ "QMC5883L 3-Axis Digital Magnetic Sensor", "group__drivers__qmc5883l.html", "group__drivers__qmc5883l" ],
    [ "SCD30 CO2, temperature and humidity sensor", "group__drivers__scd30.html", "group__drivers__scd30" ],
    [ "SDP3x temperature and differential pressure sensor", "group__drivers__sdp3x.html", "group__drivers__sdp3x" ],
    [ "SDS011 Laser Dust Sensor", "group__drivers__sds011.html", "group__drivers__sds011" ],
    [ "SHT10/SHT11/SHT15 Humidity and Temperature Sensor", "group__drivers__sht1x.html", "group__drivers__sht1x" ],
    [ "SHT2X", "group__drivers__sht2x.html", "group__drivers__sht2x" ],
    [ "SHT3x Humidity and Temperature Sensor Series", "group__drivers__sht3x.html", "group__drivers__sht3x" ],
    [ "SHTC1 Temperature and humidity sensor", "group__drivers__shtc1.html", "group__drivers__shtc1" ],
    [ "SPS30 Particulate Matter Sensor", "group__drivers__sps30.html", "group__drivers__sps30" ],
    [ "SRF02 ultrasonic range sensor", "group__drivers__srf02.html", "group__drivers__srf02" ],
    [ "SRF08 ultrasonic range sensor", "group__drivers__srf08.html", "group__drivers__srf08" ],
    [ "ST HTS221 digital Humidity Sensor", "group__drivers__hts221.html", "group__drivers__hts221" ],
    [ "STMPE811 Touchscreen Controller", "group__drivers__stmpe811.html", "group__drivers__stmpe811" ],
    [ "Si1145/6/7 UV/Ambient light/Proximity sensors", "group__drivers__si114x.html", "group__drivers__si114x" ],
    [ "Si7006/13/20/21 temperature and humidity sensors", "group__drivers__si70xx.html", "group__drivers__si70xx" ],
    [ "TCS37727 RGB Light Sensor", "group__drivers__tcs37727.html", "group__drivers__tcs37727" ],
    [ "TMP006/TMP007 Infrared Thermopile Sensor", "group__drivers__tmp00x.html", "group__drivers__tmp00x" ],
    [ "TSL2561 illuminance sensor", "group__drivers__tsl2561.html", "group__drivers__tsl2561" ],
    [ "TSL4531x Illuminance sensor", "group__drivers__tsl4531x.html", "group__drivers__tsl4531x" ],
    [ "VCNL4010/VCNL4020/VCNL4040 Proximity and Ambient Light Sensors", "group__drivers__vcnl40x0.html", "group__drivers__vcnl40x0" ],
    [ "VEML6070 UV sensor", "group__drivers__veml6070.html", "group__drivers__veml6070" ],
    [ "pH OEM sensor device driver", "group__drivers__ph__oem.html", "group__drivers__ph__oem" ],
    [ "srf04 ultra sonic range finder", "group__drivers__srf04.html", "group__drivers__srf04" ],
    [ "scd30_params.h", "scd30__params_8h.html", null ],
    [ "sdp3x_params.h", "sdp3x__params_8h.html", null ]
];