var group__config =
[
    [ "(D)TLS Credential Manager compile configurations", "group__net__credman__conf.html", "group__net__credman__conf" ],
    [ "Actuator Device Configurations", "group__config__drivers__actuators.html", "group__config__drivers__actuators" ],
    [ "Asymcute (MQTT-SN Client) compile configurations", "group__net__asymcute__conf.html", "group__net__asymcute__conf" ],
    [ "CSMA/CA helper compile configurations", "group__net__csma__sender__conf.html", "group__net__csma__sender__conf" ],
    [ "CoAP compile configurations", "group__net__coap__conf.html", "group__net__coap__conf" ],
    [ "CoRE RD Client compile configurations", "group__net__cord__conf.html", "group__net__cord__conf" ],
    [ "Core initialization compile configuration", "group__core__init__config.html", "group__core__init__config" ],
    [ "Custom ethertype", "group__net__ethertype__custom__config.html", "group__net__ethertype__custom__config" ],
    [ "DHCPv6 client compile configurations", "group__net__dhcpv6__conf.html", "group__net__dhcpv6__conf" ],
    [ "Display Device Configurations", "group__config__drivers__display.html", "group__config__drivers__display" ],
    [ "ESP common compile configurations", "group__cpu__esp__common__conf.html", "group__cpu__esp__common__conf" ],
    [ "ESP32 compile configurations", "group__cpu__esp32__conf.html", "group__cpu__esp32__conf" ],
    [ "ESP8266 compile configurations", "group__cpu__esp8266__conf.html", "group__cpu__esp8266__conf" ],
    [ "GNRC compile configurations", "group__net__gnrc__conf.html", "group__net__gnrc__conf" ],
    [ "Gcoap compile configurations", "group__net__gcoap__conf.html", "group__net__gcoap__conf" ],
    [ "IEEE802.15.4 compile configurations", "group__net__ieee802154__conf.html", "group__net__ieee802154__conf" ],
    [ "Link layer address filter compile configurations", "group__net__l2filter__conf.html", "group__net__l2filter__conf" ],
    [ "LoRa modulation compile configurations", "group__net__lora__conf.html", "group__net__lora__conf" ],
    [ "LoRaMAC compile configurations", "group__net__loramac__conf.html", "group__net__loramac__conf" ],
    [ "Miscellaneous Device Configurations", "group__config__drivers__misc.html", "group__config__drivers__misc" ],
    [ "NanoCBOR configuration header", "group__nanocbor__config.html", null ],
    [ "Nanocoap compile configurations", "group__net__nanocoap__conf.html", "group__net__nanocoap__conf" ],
    [ "Network Device Configurations", "group__config__drivers__netdev.html", "group__config__drivers__netdev" ],
    [ "Network interfaces compile configurations", "group__net__netif__conf.html", "group__net__netif__conf" ],
    [ "POSIX wrapper compile configurations", "group__config__posix.html", "group__config__posix" ],
    [ "SOCK compile configurations", "group__net__sock__conf.html", "group__net__sock__conf" ],
    [ "Sensor Device Configurations", "group__config__drivers__sensors.html", "group__config__drivers__sensors" ],
    [ "Skald compile configurations", "group__net__skald__conf.html", "group__net__skald__conf" ],
    [ "Soft Peripheral Configurations", "group__config__drivers__soft__periph.html", "group__config__drivers__soft__periph" ],
    [ "Storage Device Configurations", "group__config__drivers__storage.html", "group__config__drivers__storage" ],
    [ "Tinydtls compile time configuration", "group__tinydtls__config.html", "group__tinydtls__config" ],
    [ "USB peripheral compile time configurations", "group__usb__conf.html", "group__usb__conf" ],
    [ "WDT compile configurations", "group__drivers__periph__wdt__conf.html", "group__drivers__periph__wdt__conf" ],
    [ "Wakaama LwM2M Client configuration", "group__lwm2m__client__config.html", "group__lwm2m__client__config" ],
    [ "Wakaama LwM2M platform adaption", "group__lwm2m__platform__conf.html", "group__lwm2m__platform__conf" ]
];