var group__sys =
[
    [ "5x5 Font 'Mineplex'", "group__sys__mineplex.html", "group__sys__mineplex" ],
    [ "A minimal, non-destructive URI parser", "group__sys__uri__parser.html", "group__sys__uri__parser" ],
    [ "A terminal progress bar", "group__sys__progress__bar.html", "group__sys__progress__bar" ],
    [ "Analog data conversion utilities", "group__sys__analog__util.html", "group__sys__analog__util" ],
    [ "Arduino", "group__sys__arduino.html", "group__sys__arduino" ],
    [ "Auto-initialization", "group__sys__auto__init.html", "group__sys__auto__init" ],
    [ "Benchmark", "group__sys__benchmark.html", "group__sys__benchmark" ],
    [ "Binary coded decimal", "group__sys__bcd.html", "group__sys__bcd" ],
    [ "Bitfields", "group__sys__bitfield.html", null ],
    [ "Bloom filter", "group__sys__bloom.html", "group__sys__bloom" ],
    [ "Board reset via USB CDC ACM", "group__sys__usb__board__reset.html", "group__sys__usb__board__reset" ],
    [ "C++ compatibility with C11 atomics", "group__sys__c11__atomics__cpp__compat.html", "group__sys__c11__atomics__cpp__compat" ],
    [ "C++11 wrapper for RIOT", "group__cpp11-compat.html", "group__cpp11-compat" ],
    [ "C25519 cryptographic library", "group__pkg__c25519.html", null ],
    [ "Callback multiplexer", "group__sys__cb__mux.html", "group__sys__cb__mux" ],
    [ "Color", "group__sys__color.html", "group__sys__color" ],
    [ "Colored log module", "group__sys__log__color.html", "group__sys__log__color" ],
    [ "Crypto", "group__sys__crypto.html", "group__sys__crypto" ],
    [ "ECC", "group__sys__ecc.html", "group__sys__ecc" ],
    [ "EEPROM registration", "group__sys__eepreg.html", "group__sys__eepreg" ],
    [ "Event Queue", "group__sys__event.html", "group__sys__event" ],
    [ "FUZZING utilities", "group__sys__fuzzing.html", "group__sys__fuzzing" ],
    [ "File systems", "group__sys__fs.html", "group__sys__fs" ],
    [ "Fractional integer operations", "group__sys__frac.html", null ],
    [ "Hashes", "group__sys__hashes.html", "group__sys__hashes" ],
    [ "Helpers to manipulate partitions (slots) on internal flash", "group__sys__riotboot__slot.html", "group__sys__riotboot__slot" ],
    [ "ISR Pipe", "group__isr__pipe.html", "group__isr__pipe" ],
    [ "Interrupt handler thread", "group__sys__irq__handler.html", "group__sys__irq__handler" ],
    [ "Layered PM Infrastructure", "group__sys__pm__layered.html", "group__sys__pm__layered" ],
    [ "Lightweight Morse encoder", "group__pkg__umorse.html", null ],
    [ "Lightweight compression library", "group__pkg__heatshrink.html", null ],
    [ "Locally Unique ID Generator", "group__sys__luid.html", "group__sys__luid" ],
    [ "Math libraries and utilities", "group__sys__math.html", "group__sys__math" ],
    [ "Memory management", "group__sys__memory__management.html", "group__sys__memory__management" ],
    [ "Millisecond interval event timers", "group__sys__evtimer.html", "group__sys__evtimer" ],
    [ "NanoCBOR library", "group__pkg__nanocbor.html", "group__pkg__nanocbor" ],
    [ "Object dump", "group__sys__od.html", "group__sys__od" ],
    [ "POSIX wrapper for RIOT", "group__posix.html", "group__posix" ],
    [ "PS", "group__sys__ps.html", "group__sys__ps" ],
    [ "Phydat", "group__sys__phydat.html", "group__sys__phydat" ],
    [ "Pipe IPC", "group__sys__pipe.html", "group__sys__pipe" ],
    [ "Pointer Compression", "group__sys__util__zptr.html", "group__sys__util__zptr" ],
    [ "RFC 4122 compliant UUID's", "group__sys__uuid.html", "group__sys__uuid" ],
    [ "RIOT header helpers and tools", "group__sys__riotboot__hdr.html", "group__sys__riotboot__hdr" ],
    [ "Random", "group__sys__random.html", "group__sys__random" ],
    [ "SAUL registry", "group__sys__saul__reg.html", "group__sys__saul__reg" ],
    [ "SRAM PUF", "group__sys__puf__sram.html", "group__sys__puf__sram" ],
    [ "STDIO abstraction", "group__sys__stdio.html", "group__sys__stdio" ],
    [ "STDIO over SEGGER RTT", "group__sys__stdio__rtt.html", "group__sys__stdio__rtt" ],
    [ "STDIO over Semihosting", "group__sys__stdio__semihosting.html", "group__sys__stdio__semihosting" ],
    [ "STDIO over UART", "group__sys__stdio__uart.html", "group__sys__stdio__uart" ],
    [ "SUIT secure firmware OTA upgrade infrastructure", "group__sys__suit.html", "group__sys__suit" ],
    [ "Schedstatistics", "group__schedstatistics.html", "group__schedstatistics" ],
    [ "Semaphores", "group__sys__sema.html", "group__sys__sema" ],
    [ "Serialization", "group__sys__serialization.html", "group__sys__serialization" ],
    [ "Shell", "group__sys__shell.html", "group__sys__shell" ],
    [ "Shell commands", "group__sys__shell__commands.html", "group__sys__shell__commands" ],
    [ "Stack Smashing Protector", "group__sys__ssp.html", null ],
    [ "String formatting (fmt)", "group__sys__fmt.html", "group__sys__fmt" ],
    [ "Test interactive synchronization", "group__test__utils__interactive__sync.html", "group__test__utils__interactive__sync" ],
    [ "Thread safe ringbuffer", "group__sys__tsrb.html", "group__sys__tsrb" ],
    [ "Timers", "group__sys__xtimer.html", "group__sys__xtimer" ],
    [ "Timex", "group__sys__timex.html", "group__sys__timex" ],
    [ "Trickle Timer", "group__sys__trickle.html", "group__sys__trickle" ],
    [ "TweetNaCl high-security cryptographic library", "group__pkg__tweetnacl.html", null ],
    [ "USB", "group__usb.html", "group__usb" ],
    [ "Ultra-lightweight Javascript for Internet Of Things", "group__pkg__jerryscript.html", null ],
    [ "Unittests", "group__unittests.html", null ],
    [ "Universal Address Container", "group__sys__universal__address.html", "group__sys__universal__address" ],
    [ "Virtual File System (VFS) layer", "group__sys__vfs.html", "group__sys__vfs" ],
    [ "app_metadata", "group__sys__app__metadata.html", "group__sys__app__metadata" ],
    [ "expect() utility function", "group__test__utils__expect.html", "group__test__utils__expect" ],
    [ "iolist scatter / gather IO", "group__sys__iolist.html", "group__sys__iolist" ],
    [ "puts log module", "group__sys__log__printfnoformat.html", "group__sys__log__printfnoformat" ],
    [ "qDSA", "group__pkg__qDSA.html", null ],
    [ "riotboot flash writer", "group__sys__riotboot__flashwrite.html", "group__sys__riotboot__flashwrite" ],
    [ "small Protocol Buffers library", "group__pkg__nanopb.html", null ],
    [ "unaligned memory access methods", "group__sys__unaligned.html", "group__sys__unaligned" ],
    [ "utlist", "group__sys__ut.html", "group__sys__ut" ],
    [ "ztimer high level timer abstraction layer", "group__sys__ztimer.html", "group__sys__ztimer" ],
    [ "frac.h", "frac_8h.html", null ],
    [ "trace.h", "trace_8h.html", null ]
];