var group__cpu =
[
    [ "ARM Cortex-M common", "group__cpu__cortexm__common.html", "group__cpu__cortexm__common" ],
    [ "ARM7 CPU common", "group__cpu__arm7__common.html", "group__cpu__arm7__common" ],
    [ "Atmel ATmega CPU: common files", "group__cpu__atmega__common.html", "group__cpu__atmega__common" ],
    [ "Atmel ATmega1281", "group__cpu__atmega1281.html", "group__cpu__atmega1281" ],
    [ "Atmel ATmega1284p", "group__cpu__atmega1284p.html", "group__cpu__atmega1284p" ],
    [ "Atmel ATmega128rfa1", "group__cpu__atmega128rfa1.html", "group__cpu__atmega128rfa1" ],
    [ "Atmel ATmega2560", "group__cpu__atmega2560.html", "group__cpu__atmega2560" ],
    [ "Atmel ATmega256rfr2", "group__cpu__atmega256rfr2.html", "group__cpu__atmega256rfr2" ],
    [ "Atmel ATmega328p", "group__cpu__atmega328p.html", "group__cpu__atmega328p" ],
    [ "Atmel ATmega32u4", "group__cpu__atmega32u4.html", "group__cpu__atmega32u4" ],
    [ "Atmel SAM common", "group__cpu__sam__common.html", "group__cpu__sam__common" ],
    [ "Atmel SAM0 common", "group__cpu__sam0__common.html", "group__cpu__sam0__common" ],
    [ "Atmel SAM3", "group__cpu__sam3.html", "group__cpu__sam3" ],
    [ "Atmel SAMD21", "group__cpu__samd21.html", "group__cpu__samd21" ],
    [ "Atmel SAML21", "group__cpu__saml21.html", "group__cpu__saml21" ],
    [ "CC26xx_CC13xx common", "group__cpu__cc26xx__cc13xx__definitions.html", "group__cpu__cc26xx__cc13xx__definitions" ],
    [ "CC26xx_CC13xx common", "group__cpu__cc26xx__cc13xx.html", "group__cpu__cc26xx__cc13xx" ],
    [ "ESP Common", "group__cpu__esp__common.html", "group__cpu__esp__common" ],
    [ "ESP32", "group__cpu__esp32.html", "group__cpu__esp32" ],
    [ "ESP8266 / ESP8285", "group__cpu__esp8266.html", "group__cpu__esp8266" ],
    [ "Imagination Technologies MIPS32R2 Common", "group__cpu__mips32r2__common.html", "group__cpu__mips32r2__common" ],
    [ "LM4F", "group__cpu__lm4f120.html", "group__cpu__lm4f120" ],
    [ "Microchip MIPS common", "group__cpu__mips__pic32__common.html", "group__cpu__mips__pic32__common" ],
    [ "Microchip SAMD5x/SAME5x", "group__cpu__samd5x.html", "group__cpu__samd5x" ],
    [ "Microchip SAML10/SAML11", "group__cpu__saml1x.html", "group__cpu__saml1x" ],
    [ "NXP Kinetis", "group__cpu__kinetis.html", "group__cpu__kinetis" ],
    [ "NXP LPC1768", "group__cpu__lpc1768.html", "group__cpu__lpc1768" ],
    [ "NXP LPC2387", "group__cpu__lpc2387.html", "group__cpu__lpc2387" ],
    [ "Native", "group__cpu__native.html", "group__cpu__native" ],
    [ "Nordic nRF51 MCU", "group__cpu__nrf51.html", "group__cpu__nrf51" ],
    [ "Nordic nRF52 MCU", "group__cpu__nrf52.html", "group__cpu__nrf52" ],
    [ "Nordic nRF5x MCU", "group__cpu__nrf5x__common.html", "group__cpu__nrf5x__common" ],
    [ "Nrf52832", "group__nrf52832.html", "group__nrf52832" ],
    [ "PIC32MX", "group__cpu__mips__pic32mx.html", "group__cpu__mips__pic32mx" ],
    [ "PIC32MZ", "group__cpu__mips__pic32mz.html", "group__cpu__mips__pic32mz" ],
    [ "STM32", "group__cpu__stm32.html", "group__cpu__stm32" ],
    [ "SiFive FE310", "group__cpu__fe310.html", "group__cpu__fe310" ],
    [ "Silicon Labs EFM32/EFR32/EZR32", "group__cpu__efm32.html", "group__cpu__efm32" ],
    [ "Silicon Labs EZR32WG", "group__cpu__ezr32wg.html", "group__cpu__ezr32wg" ],
    [ "TI CC2538", "group__cpu__cc2538.html", "group__cpu__cc2538" ],
    [ "TI CC26x0", "group__cpu__cc26x0.html", "group__cpu__cc26x0" ],
    [ "TI CC26x2, CC13x2", "group__cpu__cc26x2__cc13x2.html", "group__cpu__cc26x2__cc13x2" ],
    [ "TI CC26x2, CC13x2 peripheral memory map", "group__cpu__cc26x2__cc13x2__peripheral__memory__map.html", "group__cpu__cc26x2__cc13x2__peripheral__memory__map" ],
    [ "TI CC430", "group__cpu__cc430.html", "group__cpu__cc430" ],
    [ "TI MSP430", "group__cpu__msp430__common.html", "group__cpu__msp430__common" ],
    [ "TI MSP430F", "group__cpu__msp430fxyz.html", "group__cpu__msp430fxyz" ],
    [ "eic.h", "eic_8h.html", null ]
];