var group__drivers__netdev =
[
    [ "AT86RF215 based drivers", "group__drivers__at86rf215.html", "group__drivers__at86rf215" ],
    [ "AT86RF2xx based drivers", "group__drivers__at86rf2xx.html", "group__drivers__at86rf2xx" ],
    [ "ATWINC15x0 WiFi module driver", "group__drivers__atwinc15x0.html", "group__drivers__atwinc15x0" ],
    [ "CAN Drivers", "group__drivers__can.html", "group__drivers__can" ],
    [ "CC1100/CC1100e/CC1101 Sub-GHz transceiver driver", "group__drivers__cc110x.html", "group__drivers__cc110x" ],
    [ "CC1100/CC1100e/CC1101/CC1200 common code", "group__drivers__cc1xxx.html", "group__drivers__cc1xxx" ],
    [ "CC2420 radio driver", "group__drivers__cc2420.html", "group__drivers__cc2420" ],
    [ "Differentially Operated Serial Ethernet", "group__drivers__dose.html", "group__drivers__dose" ],
    [ "Driver for stm32 ethernet", "group__drivers__stm32__common.html", null ],
    [ "ENC28J60", "group__drivers__enc28j60.html", "group__drivers__enc28j60" ],
    [ "ENCX24J600", "group__drivers__encx24j600.html", "group__drivers__encx24j600" ],
    [ "Ethernet-over-serial driver", "group__drivers__ethos.html", "group__drivers__ethos" ],
    [ "IEEE802.15.4 Driver for nRF52840 SoCs", "group__drivers__nrf52__802154.html", "group__drivers__nrf52__802154" ],
    [ "KW2x radio-driver", "group__drivers__kw2xrf.html", "group__drivers__kw2xrf" ],
    [ "KW41Z radio-driver", "group__drivers__kw41zrf.html", "group__drivers__kw41zrf" ],
    [ "MRF24J40 based drivers", "group__drivers__mrf24j40.html", "group__drivers__mrf24j40" ],
    [ "Microchip ATA8520E transceiver", "group__drivers__ata8520e.html", "group__drivers__ata8520e" ],
    [ "NRF BLE radio driver", "group__drivers__nrf5x__nrfble.html", "group__drivers__nrf5x__nrfble" ],
    [ "NRF minimal radio driver", "group__drivers__nrf5x__nrfmin.html", "group__drivers__nrf5x__nrfmin" ],
    [ "NRF24L01+ driver interface", "group__drivers__nrf24l01p.html", "group__drivers__nrf24l01p" ],
    [ "Netdev - Network Device Driver API", "group__drivers__netdev__api.html", "group__drivers__netdev__api" ],
    [ "PN532 NFC Reader", "group__drivers__pn532.html", "group__drivers__pn532" ],
    [ "RN2483/RN2903 LoRa module driver", "group__drivers__rn2xx3.html", "group__drivers__rn2xx3" ],
    [ "SLIP network device", "group__drivers__slipdev.html", "group__drivers__slipdev" ],
    [ "Semtech SX1272 and SX1276 radios driver", "group__drivers__sx127x.html", "group__drivers__sx127x" ],
    [ "Socket-based ZEP", "group__drivers__socket__zep.html", "group__drivers__socket__zep" ],
    [ "W5100 ethernet driver", "group__drivers__w5100.html", "group__drivers__w5100" ],
    [ "XBee driver", "group__drivers__xbee.html", "group__drivers__xbee" ],
    [ "netdev dummy test driver", "group__sys__netdev__test.html", "group__sys__netdev__test" ],
    [ "netdev_tap.h", "netdev__tap_8h.html", null ],
    [ "netdev_tap_params.h", "netdev__tap__params_8h.html", null ],
    [ "atwinc15x0.h", "atwinc15x0_8h.html", null ]
];