var group__drivers__periph =
[
    [ "ADC", "group__drivers__periph__adc.html", "group__drivers__periph__adc" ],
    [ "CAN", "group__drivers__periph__can.html", "group__drivers__periph__can" ],
    [ "CPUID", "group__drivers__periph__cpuid.html", "group__drivers__periph__cpuid" ],
    [ "Common peripheral initialization", "group__drivers__periph__init.html", "group__drivers__periph__init" ],
    [ "DAC", "group__drivers__periph__dac.html", "group__drivers__periph__dac" ],
    [ "EEPROM driver", "group__drivers__periph__eeprom.html", "group__drivers__periph__eeprom" ],
    [ "Flash memory driver", "group__drivers__flashrom.html", "group__drivers__flashrom" ],
    [ "Flash page driver", "group__drivers__periph__flashpage.html", "group__drivers__periph__flashpage" ],
    [ "GPIO", "group__drivers__periph__gpio.html", "group__drivers__periph__gpio" ],
    [ "HWRNG Abstraction", "group__drivers__periph__hwrng.html", "group__drivers__periph__hwrng" ],
    [ "I2C", "group__drivers__periph__i2c.html", "group__drivers__periph__i2c" ],
    [ "PWM", "group__drivers__periph__pwm.html", "group__drivers__periph__pwm" ],
    [ "Power Management", "group__drivers__periph__pm.html", "group__drivers__periph__pm" ],
    [ "Quadrature Decoder (QDEC)", "group__drivers__periph__qdec.html", "group__drivers__periph__qdec" ],
    [ "RTC", "group__drivers__periph__rtc.html", "group__drivers__periph__rtc" ],
    [ "RTT", "group__drivers__periph__rtt.html", "group__drivers__periph__rtt" ],
    [ "SPI", "group__drivers__periph__spi.html", "group__drivers__periph__spi" ],
    [ "Timer", "group__drivers__periph__timer.html", "group__drivers__periph__timer" ],
    [ "UART", "group__drivers__periph__uart.html", "group__drivers__periph__uart" ],
    [ "WDT", "group__drivers__periph__wdt.html", "group__drivers__periph__wdt" ],
    [ "usbdev - USB Device Driver API", "group__drivers__periph__usbdev.html", "group__drivers__periph__usbdev" ],
    [ "dev_enums.h", "dev__enums_8h.html", null ]
];