var group__pkg =
[
    [ "ATWINC15x0 WiFi Module Vendor Driver Package", "group__pkg__driver__atwinc15x0.html", null ],
    [ "BLAKE2 hashing library", "group__pkg__libb2.html", null ],
    [ "C25519 cryptographic library", "group__pkg__c25519.html", null ],
    [ "Cayenne Low Power Payload (LPP)", "group__pkg__cayenne-lpp.html", null ],
    [ "Cifra cryptographic library", "group__pkg__cifra.html", null ],
    [ "Color graphics library for embedded systems", "group__pkg__ucglib.html", "group__pkg__ucglib" ],
    [ "Cross platform fixed point maths library", "group__pkg__libfixmath.html", null ],
    [ "Device driver model for the Decawave Impulse Radio-Ultra Wideband (IR-UWB) transceiver(s)", "group__pkg__uwb__core.html", "group__pkg__uwb__core" ],
    [ "Driver implementation for the uwb-core driver for Decawave DW1000 transceiver", "group__pkg__uwb__dw1000.html", "group__pkg__uwb__dw1000" ],
    [ "Driver package for I2C/SPI BME680 sensor", "group__pkg__driver__bme680.html", "group__pkg__driver__bme680" ],
    [ "FAT file system", "group__pkg__fatfs.html", "group__pkg__fatfs" ],
    [ "FlatBuffers", "group__pkg__flatbuffers.html", null ],
    [ "GEMM (General Matrix Multiplication) library", "group__pkg__gemmlowp.html", null ],
    [ "GPS parser library", "group__pkg__minmea.html", null ],
    [ "HACL* High Assurance Cryptographic Library", "group__pkg__hacl.html", null ],
    [ "JSON parser library", "group__pkg__jsmn.html", null ],
    [ "JSON parser library", "group__pkg__libbase58.html", null ],
    [ "LibHydrogen cryptographic library", "group__pkg__libhydrogen.html", null ],
    [ "Lightweight ASN.1 decoding/encoding library", "group__pkg__tiny-asn1.html", null ],
    [ "Lightweight Morse encoder", "group__pkg__umorse.html", null ],
    [ "Lightweight compression library", "group__pkg__heatshrink.html", null ],
    [ "LittlevGL - Open-Source Embedded GUI Library", "group__pkg__lvgl.html", "group__pkg__lvgl" ],
    [ "Lora Serialization", "group__pkg__lora-serialization.html", null ],
    [ "Lua ported to RIOT", "group__pkg__lua.html", "group__pkg__lua" ],
    [ "Micro-ECC for RIOT", "group__pkg__micro__ecc.html", null ],
    [ "MicroPython RIOT port", "group__pkg__micropython.html", "group__pkg__micropython" ],
    [ "Microchip CryptoAuthentication Library", "group__pkg__cryptoauthlib.html", "group__pkg__cryptoauthlib" ],
    [ "Monocypher cryptographic library", "group__pkg__monocypher.html", null ],
    [ "NanoCBOR library", "group__pkg__nanocbor.html", "group__pkg__nanocbor" ],
    [ "NimBLE", "group__pkg__nimble.html", "group__pkg__nimble" ],
    [ "OpenThread network stack", "group__pkg__openthread.html", "group__pkg__openthread" ],
    [ "OpenWSN network stack", "group__pkg__openwsn.html", "group__pkg__openwsn" ],
    [ "PAHO MQTT framework", "group__pkg__paho__mqtt.html", "group__pkg__paho__mqtt" ],
    [ "QCBOR for RIOT", "group__pkg__qcbor.html", null ],
    [ "Relic toolkit for RIOT", "group__pkg__relic.html", null ],
    [ "SPI flash file system", "group__pkg__spiffs.html", "group__pkg__spiffs" ],
    [ "Semtech LoRaMAC implementation", "group__pkg__semtech-loramac.html", "group__pkg__semtech-loramac" ],
    [ "TLSF-based malloc.", "group__pkg__tlsf__malloc.html", "group__pkg__tlsf__malloc" ],
    [ "Talking LEDs - Arduino library for demonstration", "group__pkg__talking__leds.html", null ],
    [ "TensorFlow Lite", "group__pkg__tensorflow-lite.html", null ],
    [ "TinyCBOR library", "group__pkg__tinycbor.html", null ],
    [ "TinyDTLS for RIOT", "group__pkg__tinydtls.html", "group__pkg__tinydtls" ],
    [ "TweetNaCl high-security cryptographic library", "group__pkg__tweetnacl.html", null ],
    [ "Two-Level Segregated Fit memory allocator", "group__pkg__tlsf.html", null ],
    [ "U8G2 graphic library for monochome displays", "group__pkg__u8g2.html", "group__pkg__u8g2" ],
    [ "Ultra-lightweight Javascript for Internet Of Things", "group__pkg__jerryscript.html", null ],
    [ "Vendor library for EFM/EFR/EZR32 MCUs", "group__pkg__gecko__sdk.html", null ],
    [ "Wakaama LwM2M implementation", "group__pkg__wakaama.html", "group__pkg__wakaama" ],
    [ "WolfSSL Embedded SSL/TLS library", "group__pkg__wolfssl.html", null ],
    [ "Yxml XML parser", "group__pkg__yxml.html", null ],
    [ "cn-cbor", "group__pkg__cn-cbor.html", null ],
    [ "emlearn", "group__pkg__emlearn.html", null ],
    [ "libcose for RIOT", "group__pkg__libcose.html", null ],
    [ "littlefs file system", "group__pkg__littlefs.html", "group__pkg__littlefs" ],
    [ "littlefs v2.x.y file system", "group__pkg__littlefs2.html", "group__pkg__littlefs2" ],
    [ "lwIP network stack", "group__pkg__lwip.html", "group__pkg__lwip" ],
    [ "qDSA", "group__pkg__qDSA.html", null ],
    [ "small Protocol Buffers library", "group__pkg__nanopb.html", null ],
    [ "tinycrypt crypto library", "group__pkg__tinycrypt.html", null ],
    [ "uBASIC interpreter", "group__pkg__ubasic.html", null ],
    [ "uTensor", "group__pkg__utensor.html", null ]
];